# @package _group_

out_dir:                    exp
log_dir:                    tensorboard/timelag

max_train_steps:            -1
nepochs:                    50
checkpoint_epoch_interval:  20

use_amp:                    true
feats_criterion:            mse

stream_wise_loss:           false
use_detect_anomaly:         true

optim:
  optimizer:
    name:                   RAdam
    params:
      lr:                   0.001
      betas:                [0.9, 0.999]
      weight_decay:         0.0
  lr_scheduler:
    name:                   StepLR
    params:
      step_size:            20
      gamma:                0.5

resume:
  checkpoint:
  load_optimizer:           false

cudnn:
  benchmark:                false
  deterministic:            true
