### General settings
nnsvs_root:                 nnsvs
## Singer's name
spk:                        unnamed
## exp tag(for managing experiments)
tag:                        portable_enunu_training_kit

## Output directory
# All the generated labels, intermediate files, and segmented wav files
# will be saved in the following directory
out_dir:                    data

## Songs to be excluded from trainig.
exclude_songs:              []

## Lyric -> Phonemes table
## HTS-style question used for extracting musical/linguistic context from musicxml files
table_path:                 dic/kana2phonemes_002_oto2lab.table
question_path:              hed/jp_qst_crazy_mono_013_enunu_221D.hed

# Audio sampling rate
# [CAUTION] Changing sample_rate may affect the dimension number of acoustic features.
# DO NOT CHANGE this unless you know the relationship between the dim of bap and sample_rate.
sample_rate:                44100


###########################################################
#          DATA PREPARATION SETTING    (STAGE 0)          #
###########################################################
stage0:
    ## Directory of unzipped singing voice database
    db_root:                singing_database
    ### How to segment LAB and WAV before training
    # Changing this config might help you avoid "SegmentationFault" on stage 1.
    # Choices are [null, long, middle, short] (middle is recommended)
    # If "never",  LAB is not devided.
    # If "long",   LAB is devided at "pau"-"pau" or "pau""-"sil phoneme pattern.
    # If "middle", LAB is devided at the start of each <middle_frequency> "pau"s.
    # If "short",  LAB is devided at the start of each "pau" phoneme.
    segmentation_mode:      middle
    middle_frequency:       3

    # Choices are [strict, middle, lenient]
    vowel_duration_check:   middle


###########################################################
#          FEATURE EXTRACTION SETTING  (STAGE 1)          #
###########################################################
timelag_features:           defaults
duration_features:          defaults
acoustic_features:          static_deltadelta
# optional arg of "aperiodicity = pyworld.d4c()" in nnsvs/data/data_source.py (line 155)
# d4c_threshold:            0.58

trajectory_smoothing:        false
trajectory_smoothing_cutoff: 50

# test arguments for proper f0 range
f0_floor: 150
f0_ceil: 700

# test argument for correct VUV
correct_vuv: false

# test argument for relative_f0
relative_f0: true

###########################################################
#          TRAINING SETTING  (STAGE 2 - STAGE 4)          #
###########################################################

# Models
# To customize, put your config or change ones in
# conf/train/{timelag,duration,acoustic}/ and
# specify the config name below
# NOTE: *_model: model definition, *_train: general train configs, *_data: data configs (e.g., batch size)

acoustic_model:             acoustic_custom
acoustic_train:             myconfig
acoustic_data:              myconfig

duration_model:             duration_custom
duration_train:             myconfig
duration_data:              myconfig

timelag_model:              timelag_custom
timelag_train:              myconfig
timelag_data:               myconfig

# Pretrained model dir (leave empty to disable)
# pretrained_expdir:          exp/ritsu_enunu_rmdn_0831
pretrained_expdir:

timelag_hydra_optuna_sweeper_args:
timelag_hydra_optuna_sweeper_n_trials: 100
duration_hydra_optuna_sweeper_args:
duration_hydra_optuna_sweeper_n_trials: 100
acoustic_hydra_optuna_sweeper_args:
acoustic_hydra_optuna_sweeper_n_trials: 100

###########################################################
#         SYNTHESIS SETTING             (STAGE 6)         #
###########################################################
timelag_synthesis:          defaults
duration_synthesis:         defaults
acoustic_synthesis:         defaults

# latest.pth or best.pth are recommended
timelag_eval_checkpoint:    best_loss.pth
duration_eval_checkpoint:   best_loss.pth
acoustic_eval_checkpoint:   best_loss.pth
